### ISSUE TITLE
edison in  "iothub_client_sample_mqtt_dm/CMakeLists.txt" 

### ISSUE THREAD

**Issue by mgiuncato** [Azure/azure-iot-sdks-preview#3]
where is  used define "edison" , maybe there is another iotdm_edison_sample for intel edison that I didn't find or you plan to release a specific version  ?
i'm going to study the dm M14 version to port to intel edison, am i right ?
tks 
Marco

**Comment by bzurcher** [comment]
Hey Marco, for the 9/26 DM public preview update, we deprecated the previous sample support for the Intel Edison which is why you can no longer find it.  We hope to fix this in the near future but don't have a timeframe to share.

In the coming days, however, we will be releasing an equivalent sample for the Raspberry Pi 2/3 which will use the updated DM public preview functionality.  As you're aware, the Pi is much more available, cheaper, and has the strongest customer interest.  

Stay tuned for the Pi sample update, and let me know if you have any other questions/concerns.

**Comment by anporumb** [comment]
Closing after more than 5 days with no feedback.

**Comment by mgiuncato** [comment]
Sorry for delay I was OOO.
ok, I'm waiting for equivalent sample for PI, hoping for a simple move to Intel Edison architecture.

however I'm worried about the preference of Raspberry , because we are in final test of our [` Intel based product,`](http://www.smarthesia.com/our-tecnology) started in 2015 that will leave to customer in the finale release 4rd qt of 2016.

Does you intend that Microsoft IOT is leaving support to Intel Edison preferring Raspberry ? It's a  surprise for me, we are in close relationship with Intel and Microsoft too for our Edison based Project, we were ad MakerFaire  2016 at Rome in Intel stand to show it. 
more, the product in prerelease verison is present in various customer evaluation installation. 
The failure of IOT DM platform started 30/sept gave a non positive feeling on our job and IOT Azure. We have to work to fix it in the new DM architecture

I appreciate deeper information about this and of release timeframe.
